### ISSUE TITLE
location gets deleted after status change, if it contains a comma

### ISSUE THREAD

**Issue by fs1** [wrk-fmd/CoCeSo#115]
If the location of a relocation event contains a comma, the location gets deleted once the status of an associated unit is changed:

[![video]()](https://user-images.githubusercontent.com/1917852/134859713-86949dab-30e0-426a-932c-abca27d77c06.mp4)

This happens also to all other events as it seems - I added a comma after "Rud Ev" for demonstration purposes:
![image](https://user-images.githubusercontent.com/1917852/134822343-747541e3-7c46-42c6-9e60-619048c93b85.png)
after the status change:
![image](https://user-images.githubusercontent.com/1917852/134822367-970be022-483e-4bf7-8125-75401c81e4ab.png)

**Comment by at-dro** [comment]
Fixed in 0d5ef96.

Issue was caused by the title line and and additional lines not written to the database at all, but was only visible when these properties are set at all (i.e., something in the text cannot be parsed as street or city at all, as is the case with commas) AND data is loaded from the database directly instead of cached Hibernate data (which apparently only happens for status updates, but not other updates).
