### ISSUE TITLE
GeoBroker Information Sheet

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/CoCeSo#13]
As an operator I want to create a PDF file containing the GeoBroker references for Location Updates (see #12)
The PDF contains one page per mobile unit.

Each page provides following data:
* Display name of the unit (Title of the page)
* QR code with an URL to the public accessible frontend to provide location updates
  * The external unit id and the token are encoded in the URL. The URL parameters are different for each unit.

Configuration:
* A global property provides the base URL for the frontend.

See [zxing project](https://github.com/zxing/zxing/) for QR code generation.

**Comment by heinrichmartin** [comment]
This is not something that Coceso must do, could be another app, too (even static html+js and print from browser, e.g. https://github.com/davidshimjs/qrcodejs - I have a private copy with a few improvements).

**Comment by robo-w** [comment]
The idea was to create a batch PDF for a complete concern of CoCeSo. This PDF can then be printed at once, and you receive all information sheets for all units.
Of course it can be a static javascript page for rendering. Is it possible to create a print-optimized, page-oriented output with QR codes with the qrcodejs library?
If it solved in a complete separate application, the data has to be synchronized from CoCeSo.

**Comment by heinrichmartin** [comment]
Ok since we changed to Coceso being the master of the data (creating UUIDs).

Is creation of PDF already available in the Coceso code-base, then it seems easiest to do it this way. Otherwise, the data for static html+js could be added to the private interface of the GeoBroker. Concerning page-oriented, see the print preview of https://www.lvsys.com/how-to-add-page-breaks-to-html-in-articles (optionally wrapped in `@media print`).

**Comment by robo-w** [comment]
Implemented in another repo.
